#+Title: My personal Nixos configuration with flakes
#+Author: Valentino Bocchetti
#+STARTUP: overview

* Table of contents :toc:
- [[#about][About]]
- [[#structure][Structure]]
- [[#quick-start][Quick start]]
- [[#todo-list][TODO-LIST]]
  - [[#add-an-option-to-btrfs-configuration-work-in-progress][Add an option to btrfs configuration (work-in-progress)]]

* About
The entire system configuration is written in Nix. It is composed of a host specific configuration ([[file:host/home/][home]] & [[file:host/laptop/][laptop]]) that includes stuff  specific for my different hosts; a [[file:common/][common]] directory containing shared config files between all my machines, and a [[file:cachix/][cachix]] directory in order to make less expensive switching to a new generation ([[https://app.cachix.org/cache/nix-community][Installation guide]]).

A convenience [[file:nix-install.sh][script]] is provided to setup the system on the live ISO.
* Structure
```bash
.
├── nix                                 # Niv directory
├── nixos                               # NixOS system configurations
│  ├── bootstrap.sh                       # Bootstrap script
│  ├── codexlab-ca.crt                    # Homelab internal CA certificate
│  ├── common.nix                         # Shared config
│  ├── frenchpenguin                      # Frenchpenguin (work laptop) specific configs
│  |  ├── configuration.nix
│  |  └── hardware-configuration.nix
│  ├── install.sh                         # Install script
│  └── microwave                          # Microwave (home desktop) specific configs
│     ├── configuration.nix
│     └── hardware-configuration.nix
├── nixpkgs                             # Home-Manager configuration
│  ├── common.nix                         # Shared config
│  ├── config.nix                         # Nixpkgs config
│  ├── configs                            # Miscellaneous config files
│  ├── home.nix                           # Main HM config (only imports common.nix and ${hostname}.nix)
│  ├── hosts                              # System-specific configurations
│  │  └── frenchpenguin.nix                 # Frenchpenguin (work laptop) specific configs
│  ├── images                             # Various images
│  ├── install.sh                         # Install script
│  ├── modules                            # Reusable components that install and configure various aspects of the system
│  │  ├── alacritty.nix                     # Alacritty (terminal emulator)
│  │  ├── bluetooth.nix                     # Bluetooth configuration (for hosts that support it)
│  │  ├── coreutils.nix                     # System core components (vim, exa, environment variables, etc)
│  │  ├── desktop.nix                       # GUI-related software (chats, email, Steam, file explorer, GTK theme, etc) [1]
│  │  ├── development.nix                   # Sofware development tools (editors, compilers, language runtimes, etc)
│  │  ├── email.nix                         # Email setup and tools
│  │  ├── fish.nix                          # Fish shell
│  │  ├── git.nix                           # Git
│  │  ├── gpg.nix                           # GPG and Keybase
│  │  ├── greenclip.nix                     # Greenclip config (clipboard manager [2])
│  │  └── xmonad.nix                        # XMonad configuration (includes DE-less tools like Rofi, Picom, Dunst, etc)
│  ├── pkgs                               # Custom packages not available on nixpkgs
│  └── xmonad                             # XMonad configuration
│     ├── xmobar.hs                         # XMobar config
│     ├── xmonad-session-rc                 # Symlinked to `.xprofile` for starting up services and preparing the graphical environment
│     └── xmonad.hs                         # XMonad main config
└── shell.nix                             # Nix Shell config
```

* Quick start
1. Download the latest build of [[https://nixos.org/download.html][Nixos]].
2. Boot into the installer.
3. Start the installation script in order to get a working installation (=./nix-install.sh -s=) (*NB* currently supported only ext4 in this configuration)
4. Enable nix-flakes with ~nix-shell -p git nixFlakes~
5. Clone the repository: ~git clone https://github.com/luftmensch-luftmensch/Nixos~  to =/mnt/etc/nixos=
6. Install NixOS: =nixos-install --root /mnt --flake /mnt/etc/nixos#XYZ=, where /XYZ is [the host you want to install]/
7. Reboot!
8. Change your ~root~ and ~$USER~ passwords!
9. Enjoy!
* TODO-LIST
** TODO Add an option to btrfs configuration (work-in-progress)
