#+OPTIONS: date:nil title:nil toc:nil author:nil
#+STARTUP: overview
* My personal Nixos configuration with flakes
#+BEGIN_HTML
<div align="center">

  <!-- License -->
  <a href="https://github.com/luftmensch-luftmensch/Nixos/LICENSE"
          ><img
              src="https://img.shields.io/badge/License-GPL_v3-blue.svg?style=for-the-badge&color=red"
              alt="License"
      /></a>

  <!-- Nixos Version -->
  <a href="https://nixos.org/"
          ><img
              src="https://img.shields.io/badge/NixOS-v21.11-blue.svg?style=for-the-badge&logo=NixOS&logoColor=white"
              alt="Nixos Version"
      />

  <!-- Repository Size -->
  <a href="https://github.com/luftmensch-luftmensch/Nixos/archive/refs/heads/main.zip"
          ><img
              src="https://img.shields.io/github/repo-size/luftmensch-luftmensch/Nixos?style=for-the-badge"
              alt="GitHub repository size"
      /></a>

  <!-- Last commit -->
  <a href="https://github.com/luftmensch-luftmensch/Nixos/commits/main"
          ><img
              src="https://img.shields.io/github/last-commit/luftmensch-luftmensch/Nixos?style=for-the-badge"
              alt="Last commit"
      /></a>
 <!-- Work on my machine -->
 <a href="https://img.shields.io/badge/WORKS%20ON-MY%20MACHINE-red?style=for-the-badge"
           ><img
             src="https://img.shields.io/badge/WORKS%20ON-MY%20MACHINE-red?style=for-the-badge"
             alt="Work on my machine"
      /></a>
</div>
#+END_HTML
* Table of contents
- [[#about][About]]
- [[#quick-start][Quick start]]
* About
The entire system configuration is written in Nix. It is composed of a host specific configuration ([[file:host/home/][home]] & [[file:host/laptop/][laptop]]) that includes stuff  specific for my different hosts; a [[file:common/][common]] directory containing shared config files between all my machines, and a [[file:cachix/][cachix]] directory in order to make less expensive switching to a new generation ([[https://app.cachix.org/cache/nix-community][Installation guide]]).

A convenience [[file:nix-install.sh][script]] is provided to setup the system on the live ISO (both ext4 and zfs installation is supported).
* Quick start
1. Download the latest build of [[https://nixos.org/download.html][Nixos]].
2. Boot into the installer.
3. Start the installation script in order to get a working installation (=./nix-install.sh -s= for ext4 installation, =./zfs-nix-install -s= for zfs installation)
4. Enable nix-flakes with ~nix-shell -p git nixFlakes~
5. Clone the repository: ~git clone https://github.com/luftmensch-luftmensch/Nixos~  to =/mnt/etc/nixos=
6. Install NixOS: =nixos-install --root /mnt --flake /mnt/etc/nixos#XYZ=, where /XYZ is [the host you want to install]/
7. Reboot!
8. Change your ~root~ and ~$USER~ passwords!
9. Enjoy!
