#+OPTIONS: date:nil title:nil toc:nil author:nil
#+STARTUP: overview
* My personal Nixos configuration with flakes
#+BEGIN_HTML
<div align="center">

  <!-- License -->
  <a href="https://github.com/luftmensch-luftmensch/Nixos/LICENSE"
          ><img
              src="https://img.shields.io/badge/License-GPL_v3-blue.svg?style=for-the-badge&color=red"
              alt="License"
      /></a>

  <!-- Nixos Version -->
  <a href="https://nixos.org/"
          ><img
              src="https://img.shields.io/badge/NixOS-v21.11-blue.svg?style=for-the-badge&logo=NixOS&logoColor=white"
              alt="Nixos Version"
      />

  <!-- Repository Size -->
  <a href="https://github.com/luftmensch-luftmensch/Nixos/archive/refs/heads/main.zip"
          ><img
              src="https://img.shields.io/github/repo-size/luftmensch-luftmensch/Nixos?style=for-the-badge"
              alt="GitHub repository size"
      /></a>

  <!-- Last commit -->
  <a href="https://github.com/luftmensch-luftmensch/Nixos/commits/main"
          ><img
              src="https://img.shields.io/github/last-commit/luftmensch-luftmensch/Nixos?style=for-the-badge"
              alt="Last commit"
      /></a>
 <!-- Work on my machine -->
 <a href="https://img.shields.io/badge/WORKS%20ON-MY%20MACHINE-red?style=for-the-badge"
           ><img
             src="https://img.shields.io/badge/WORKS%20ON-MY%20MACHINE-red?style=for-the-badge"
             alt="Work on my machine"
      /></a>
</div>
#+END_HTML
* Table of contents
- [[#about][About]]
- [[#quick-start][Quick start]]
* About
This is my configuration for NixOS, meant to harmonize my different systems.

-----
This is *not* necessarily an example of good practices. This is what I am (probably) currently using.

The purpose of making this repository public is for me to be able to easily share my current configuration files with others. It is not expected that anyone would use these files verbatim. I update files frequently, often multiple times per day, and at any given point, some files might be broken. I often push commits just so I can easily move files from one computer to another to continue working on them. I will make tags when I think my setup is stable enough for others to use.
-----

The entire system configuration is written in Nix. It is composed of a host specific configuration ([[file:host/home/][home]] & [[file:host/laptop/][laptop]]) that includes stuff  specific for my different hosts; a [[file:common/][common]] directory containing shared config files between all my machines, and a [[file:cachix/][cachix]] directory in order to make less expensive switching to a new generation ([[https://app.cachix.org/cache/nix-community][Installation guide]]).

A convenience [[file:nix-install.sh][script]] is provided to setup the system on the live ISO (both ext4 and zfs installation is supported).
* Quick start
1. Download the latest build of [[https://nixos.org/download.html][Nixos]].
2. Boot into the installer.
3. Start the installation script in order to get a working installation (=./nix-install.sh -s= for ext4 installation, =./zfs-nix-install -s= for zfs installation)
4. Enable nix-flakes with ~nix-shell -p git nixFlakes~
5. Clone the repository: ~git clone https://github.com/luftmensch-luftmensch/Nixos~  to =/mnt/etc/nixos=
6. Install NixOS: =nixos-install --root /mnt --flake /mnt/etc/nixos#XYZ=, where /XYZ is [the host you want to install]/
7. Reboot!
8. Change your ~root~ and ~$USER~ passwords!
9. Enjoy!
* Some useful guide
** Written guide / blogs (Flakes)
1. ~man nix-flake~ (22.05);
2. [[https://nixos.wiki/wiki/Flakes][Flakes]];
3. [[https://nixos.org/guides/nix-pills/][Nix pills]];
4. [[https://www.tweag.io/blog/2020-05-25-flakes/][Nix Flakes - Part 1: Introduction and tutorial]];
5. [[https://www.tweag.io/blog/2020-06-25-eval-cache/][Nix Flakes - Part 2: Evaluation caching]];
6. [[https://www.tweag.io/blog/2020-07-31-nixos-flakes/][Nix Flakes - Part 3: Managing Nixos Systems]];
7. [[https://xeiaso.net/blog/nix-flakes-1-2022-02-21][Xe on Flakes: Introduction]];
8. [[https://xeiaso.net/blog/nix-flakes-2-2022-02-27][Xe on Flakes: Packages and How to use Them]];
9. [[https://serokell.io/blog/practical-nix-flakes][Pratical Nix Flakes by Serokell]];
10. [[https://www.yanboyang.com/nixflakes/][Nix flakes by Yanboyang]];
11. [[https://ianthehenry.com/posts/how-to-learn-nix/][How to learn Nix]];
12. [[https://garnix.io/blog/converting-to-flakes][Nix flakes, and how to convert to them]];
** Video sources
1. [[https://www.youtube.com/watch?v=90P-Ml1318U][Jon R tutorial]];
2. [[https://www.youtube.com/playlist?list=PL-saUBvIJzOkjAw_vOac75v-x6EzNzZq-][Will T tutorials]];
3. [[https://www.youtube.com/watch?v=AGVXJ-TIv3Y][Nixos Setup Guide]];
4. [[https://www.youtube.com/watch?v=QXUlhnhuRX4][Jorg Thalheim: Nix flakes 101]];
** Nix Flake templates for various languages
+ [[https://github.com/serokell/templates][Templates by serokell (haskell, infra, python, rust)]];
+ [[https://github.com/lukebfox/nix-flake-templates][Templates by lukebfox (rust, python, elixir)]];
+ [[https://github.com/rdk31/nix-flake-templates][Templates by rdk31 (python, rust)]];
** Installation guide
1. [[https://jdisaacs.com/blog/nixos-config/][Nixos configuration with flakes]];
** Useful links
+ [[https://nixos.org/manual/nixpkgs/stable/#chap-functions][Nixpkgs Functions reference]];
+ [[https://nixos.org/manual/nix/stable/#ch-expression-language][Nix Expression Language]];
** Useful nix dotfiles
+ [[https://github.com/hlissner/dotfiles][hlissner/dotfiles]];
+ [[https://github.com/NobbZ/nixos-config][NobbZ/nixos-config]];
