# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot = {
    initrd = {
      luks.devices."nix-enc" = {
        device = "/dev/disk/by-uuid/f433d760-8999-4527-9094-27ba78ec651a"; #/dev/nvme0n1p2 (blkid)
        preLVM = true;
        allowDiscards = true;  
      };

      availableKernelModules = [ "nvme" "ehci_pci" "xhci_pci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];

      kernelModules = [ "dm-snapshot" ];
    };

    kernelModules = [ "kvm-amd" ];
    extraModulePackages = [ ];
    
  };


  fileSystems."/" =
    { #device = "/dev/disk/by-uuid/0289ac7e-7a6a-4826-93a0-80f1d1a2aa1b";
      device = "/dev/disk/by-label/root";

      fsType = "ext4";
      options = [ "noatime" "nodiratime" "discard" ];
    };

  fileSystems."/boot" =
    { #device = "/dev/disk/by-uuid/7312-F7CD";
      device = "/dev/disk/by-label/boot";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-label/SWAP"; }
    ];

}
